variable "rt_pub" {}
variable "aws_project" {}
variable "aws_prefix" {}
variable "tag_project" {}
variable "vpc_id" {}
variable "igw" {}
variable "mask_priv" {}
variable "mask_pub" {}
variable "cidr_priv" {}
variable "cidr_pub" {}
variable "enable_rds" {}
variable "enable_redis" {}
variable "config_rds" {}
variable "aws_env" {}
variable "rt-priv-peering" {}
variable "rt-pub-peering" {}
variable "aws_vpn_gateway" {}
variable "route_propagation_priv" {}
variable "route_propagation_pub" {}
