variable "tag_project" {}
variable "alb_internal" {}
variable "subnet_pub" {}
variable "subnet_priv" {}
variable "bucket_log" {}
variable "aws_prefix" {}
variable "aws_project" {}
variable "port_app" {}
variable "vpc_id" {}
variable "random_value" {}
variable "aws_cert" {}
variable "type_alb" {}
variable "security_groups" {}
variable "config_alb" {}
variable "config_nlb" {}
variable "alpn_policy" {}
variable "enable_apigateway_private" {}
variable "additional_certs" {}
