variable "vpc_id" {}
variable "tag_project" {}
variable "aws_project" {}
variable "aws_prefix" {}
variable "enable_rds" {}
variable "enable_alb" {}
variable "enable_redis" {}
variable "enable_apigatewayv2" {}
variable "enable_vpc_link" {}
variable "enable_vpc_endpoint" {}
variable "port_app" {}
variable "port_rds" {}
variable "port_redis" {}
variable "port_apigateway" {}
variable "ingress_redis" {}
variable "ingress_app" {}
variable "ingress_rds" {}
variable "ingress_alb" {}
variable "ingress_apigateway" {}
variable "ingress_vpc_endpoint" {}
